# Generated by Django 4.2.5 on 2023-10-10 23:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1885)])),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], default='A', max_length=100)),
                ('station', models.CharField(choices=[('1', 'Posto 1'), ('2', 'Posto 2')], max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('F', 'Finished'), ('C', 'Canceled')], default='IP', max_length=100)),
                ('automobileFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automobile_maintenance', to='app.automobile')),
                ('dropoff_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_date', to='app.availability')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('producer_name', models.CharField(max_length=100)),
                ('producer_key', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payment', models.CharField(choices=[('PIX', 'PIX'), ('BS', 'BANK SLIP'), ('CC', 'CREDIT CARD'), ('DC', 'DEBIT CARD')], max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Canceled'), ('A', 'Approved')], default='P', max_length=100)),
                ('maintenanceFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_maintenance', to='app.maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Employee'), ('U', 'User'), ('M', 'Master')], max_length=100)),
                ('image_link', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employeeFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_service', to='app.myuser')),
                ('maintenanceFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_maintenanceService', to='app.maintenance')),
                ('serviceFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_maintenanceService', to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenanceFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_maintenanceProduct', to='app.maintenance')),
                ('productFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_maintenanceProduct', to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='userFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maintenance', to='app.myuser'),
        ),
    ]
