# Generated by Django 4.2.4 on 2023-08-22 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('air_date', models.DateTimeField()),
                ('episode', models.CharField(max_length=150)),
                ('characters', models.TextField()),
                ('url', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('residents', models.TextField()),
                ('url', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='Unknown', max_length=10)),
                ('species', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Unknown', max_length=10)),
                ('image', models.TextField()),
                ('episodes', models.TextField()),
                ('url', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.locations')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='main.locations')),
            ],
        ),
    ]
