# Generated by Django 4.2.4 on 2023-08-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
        migrations.RenameModel(
            old_name='Episodes',
            new_name='Episode',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
