# Generated by Django 4.2.4 on 2023-08-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_characters_character_rename_episodes_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Genderless', 'Genderless'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('Dead', 'Dead'), ('Unknown', 'Unknown'), ('Alive', 'Alive')], default='Unknown', max_length=10),
        ),
    ]
