# Generated by Django 4.2.4 on 2023-08-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_character_gender_alter_character_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='origin',
        ),
    ]
