# Generated by Django 4.2.4 on 2023-08-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_character_origin_alter_character_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
