# Generated by Django 3.2.12 on 2022-04-27 23:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivelAcesso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=1000)),
                ('prazo', models.DateTimeField()),
                ('dataInicio', models.DateTimeField(default=datetime.datetime(2022, 4, 27, 23, 22, 28, 935030, tzinfo=utc))),
                ('dataFim', models.DateTimeField(blank=True, null=True)),
                ('idAmbienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=80)),
                ('fone', models.CharField(max_length=15)),
                ('ativo', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=1500, null=True)),
                ('uid', models.CharField(blank=True, max_length=55, null=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('idNivelAcessoFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='main.cargos')),
                ('idUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarefasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTarefaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarefas')),
                ('idUsuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='TarefasStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 23, 22, 28, 936031, tzinfo=utc), null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('idStatusFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('idTarefaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarefas')),
            ],
        ),
        migrations.AddField(
            model_name='tarefas',
            name='idSolicitanteFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='idStatusFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=55, null=True)),
                ('image', models.CharField(blank=True, max_length=1500, null=True)),
                ('idStatusFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('idTarefaFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tarefas')),
            ],
        ),
    ]
