# Generated by Django 3.2.12 on 2023-05-28 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220614_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 13, 29, 35, 703745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 28, 13, 29, 35, 704746, tzinfo=utc), null=True),
        ),
    ]
