# Generated by Django 4.2.5 on 2023-09-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_payment_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='diaria',
            new_name='daily',
        ),
    ]
