# Generated by Django 4.2.5 on 2023-09-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('purchaseValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('people', models.IntegerField()),
                ('hasPet', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=400, null=True)),
                ('score', models.IntegerField(null=True)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUserBooking', to='main.customuser')),
                ('tripFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='main.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'BOLETO'), ('CC', 'CARTÃO DE CRÉDITO'), ('CD', 'CARTÃO DE DÉBITO')], max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado'), ('A', 'APROVADO')], default='P', max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('bookingFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingPayment', to='main.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bookingFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingAvailability', to='main.booking')),
                ('tripFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripAvailability', to='main.trip')),
            ],
        ),
    ]
