# Generated by Django 4.2.5 on 2023-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_booking_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purchaseValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
