# Generated by Django 4.2.5 on 2023-10-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_availability_bookingfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
