# Generated by Django 4.2.5 on 2023-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_booking_purchasevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado(a)'), ('A', 'Aprovado(a)')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purchaseValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('PIX', 'PIX'), ('BS', 'BANK SLIP'), ('CC', 'CREDIT CARD'), ('CD', 'DEBT CARD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado(a)'), ('A', 'Aprovado(a)')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='daily',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
