# Generated by Django 4.2.5 on 2023-10-01 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_booking_status_alter_booking_purchasevalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
